version: "3"

services:
  app:
    container_name: number_place
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
    ports:
      - ${NUMBER_PLACE_ANALYSIS_APPLICATION_PORT}:3000
    tty: true
